/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospi;

import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buscador = new javax.swing.JComboBox();
        bus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 226, 251));

        buscador.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        buscador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-SELECCIONAR-", "Paciente", "Doctor", "Hospital" }));
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });

        bus.setText("buscar");
        bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Buscador");

        salir.setBackground(new java.awt.Color(153, 0, 153));
        salir.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospi/h.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elige una opción de busqueda:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1)))
                        .addGap(30, 30, 30)
                        .addComponent(bus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(bus))
                .addGap(41, 41, 41)
                .addComponent(salir)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        if (buscador.getSelectedItem().toString().equals("-SELECCIONES-")) {
           
        
        }
    }//GEN-LAST:event_buscadorActionPerformed

    private void busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busActionPerformed

        Paciente pa1 = new Paciente(25, "Alejandro", "Diaz", 20, "Carrera 20 #14-01", "Masculino", "Hospital mayor", "Luis Ramos", "Migraña");
        Paciente pa2 = new Paciente(56, "Maria", "Cubillos", 10, "Calle 58B #65-85", "Femenino", "Hospital mayor", "Luis Ramos", "Dolor abdominal");
        Paciente pa3 = new Paciente(98, "Humberto", "Cruz", 65, "Calle 76A #35-45", "Masculino", "Hospital macarena", "Mario Lopez", "Calculos en los riñones");
        Paciente pa4 = new Paciente(10, "Lorena", "Perez", 33, "Carrera 140 #45-45", "Femenino", "Hospital macarena", "Mario Lopez", "Fractura de pie");
        Paciente pa5 = new Paciente(150, "Carolina", "Rubiano", 45, "Calle 08 #184-50", "Femenino", "Hospital canicas", "Leonardo Camelo", "Diabetes");
        Paciente pa6 = new Paciente(588, "carlos", "Ramos", 45, "carrera 13B #20-68", "Masculino", "Hospital canicas", "Leonardo Camelo", "Paperas");
        Doctor do1 = new Doctor(63, "Luis Ramos", "Alejandro", "Diaz", 20, "Carrera 20 #14-01", "Masculino", "Hospital mayor", "Migraña");
        Doctor do2 = new Doctor(63, "Luis Ramos", "Maria", "Cubillos", 10, "Calle 58B #65-85", "Femenino", "Hospital mayor", "Dolor abdominal");
        Doctor do3 = new Doctor(105, "Mario Lopez", "Humberto", "Cruz", 65, "Calle 76A #35-45", "Masculino", "Hospital macarena", "Calculos en los riñones");
        Doctor do4 = new Doctor(105, "Mario Lopez", "Lorena", "Perez", 33, "Carrera 140 #45-45", "Femenino", "Hospital macarena", "Fractura de pie");
        Doctor do5 = new Doctor(12, "Leonardo Camelo", "Carolina", "Rubiano", 45, "Calle 08 #184-50", "Femenino", "Hospital canicas", "Diabetes");
        Doctor do6 = new Doctor(12, "Leonardo Camelo", "carlos", "Ramos", 45, "carrera 13B #20-68", "Masculino", "Hospital canicas", "Paperas");
        InterfaceHospital a = new Hospital1();
        InterfaceHospital b = new Hospital2();
        InterfaceHospital c = new Hospital3();
        if (buscador.getSelectedItem().toString().equals("Paciente")) {
            JOptionPane.showMessageDialog(null, "pacientes atendidos");
            pa1.mostrarDatos();
            pa2.mostrarDatos();
            pa3.mostrarDatos();
            pa4.mostrarDatos();
            pa5.mostrarDatos();
            pa6.mostrarDatos();
        } else {
            if (buscador.getSelectedItem().toString().equals("Doctor")) {
                JOptionPane.showMessageDialog(null, "médico datos de los pacientes que atendio");
                do1.mostrarDatos();
                do2.mostrarDatos();
                do3.mostrarDatos();
                do4.mostrarDatos();
                do5.mostrarDatos();
                do6.mostrarDatos();

            } else {
                if (buscador.getSelectedItem().toString().equals("Hospital")) {
                    JOptionPane.showMessageDialog(null, "Nombre del centro de servicio y pacientes atendidos");
                    Hospital1 h1 = new Hospital1();
                    h1.Hospital();
                    Hospital2 h2 = new Hospital2();
                    h2.Hospital();
                     Hospital3 h3 = new Hospital3();
                    h3.Hospital();

                }
            }
        }
    }//GEN-LAST:event_busActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
          System.exit(WIDTH);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bus;
    private javax.swing.JComboBox buscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
